name: Publish rpm from master

on:
  push:

# will produce tags in format fiware/orion:<SEMVER>-PRE-<INCREASING-NUMBER>, f.e. fiware/orion:2.6.0-PRE-12
env:
  CI_IMAGE: fiware/orion-ci:rpm8

jobs:
  build-rpm:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build & Push
        id: rpm_build
        run: |
          ./.github/build-and-push-rpm.sh ${{ secrets.NEXUS_PASSWORD }} 
          
