name: Publish rpm from master

on:
  push:

# will produce tags in format fiware/orion:<SEMVER>-PRE-<INCREASING-NUMBER>, f.e. fiware/orion:2.6.0-PRE-12
env:
  CI_IMAGE: fiware/orion-ci:rpm8

jobs:
  build-rpm:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build & Push
        id: rpm_build
        run: |
          docker run -e BROKER_RELEASE=nightly -v $(pwd):/opt/orion --workdir=/opt/orion fiware/orion-ci:rpm8 make rpm
          version=$(cat $(pwd)/src/app/contextBroker/version.h | grep ORION_VERSION | awk '{ print $3}' | sed 's/"//g')
          echo ${version}
          curl -v -f -u telefonica-github:${{ secrets.NEXUS_PASSWORD }} --upload-file $(pwd)/rpm/RPMS/x86_64/contextBroker-${version}-nightly.x86_64.rpm https://nexus.lab.fiware.org/repository/el/8/x86_64/nightly/contextBroker-${version}-nightly.x86_64.rpm

