name: Valgrind Tests

on:
  push:
  pull_request:
    branches:
      - master

env:
   TEST_IMAGE_NAME: fiware/orion-ci:rpm8

jobs:
  valgrind-1:
    runs-on: ubuntu-18.04

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

      mosquitto:
        # Needed by MQTT notification tests
        image: eclipse-mosquitto:1.6.7
        ports:
        - 1883:1883

      mosquitto-extra:
        # Needed by MQTT notification tests (multi broker)
        image: eclipse-mosquitto:1.6.7
        ports:
        - 1884:1883

    steps:
      - uses: actions/checkout@v2

      - name: Run valgrind test
        # By the moment FT_FROM_IX and FT_TO_IX doesn't work with valgrind
        run: |
          docker run  --privileged --network host -t --rm -e FT_FROM_IX=1 -e FT_TO_IX=2000 -v $(pwd):/opt/fiware-orion ${{ env.TEST_IMAGE_NAME }} build -miqts valgrind


